// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerliftMeet.Database;

#nullable disable

namespace PowerliftMeet.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615134043_dateonly")]
    partial class dateonly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("GenderId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LiftCardId")
                        .HasColumnType("uuid");

                    b.Property<int>("LiftType")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LiftCardId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.LiftCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetAthleteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetAthleteId");

                    b.ToTable("LiftCards");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Meet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Meets");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.MeetAthlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeightClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("MeetId");

                    b.HasIndex("WeightClassId");

                    b.ToTable("MeetAthletes");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.WeightClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("WeightClasses");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Athlete", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerliftMeet.Database.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Attempt", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.LiftCard", "LiftCard")
                        .WithMany()
                        .HasForeignKey("LiftCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiftCard");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.Flight", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.Meet", "Meet")
                        .WithMany()
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.LiftCard", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.MeetAthlete", "MeetAthlete")
                        .WithMany()
                        .HasForeignKey("MeetAthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetAthlete");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.MeetAthlete", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerliftMeet.Database.Entities.Meet", "Meet")
                        .WithMany()
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerliftMeet.Database.Entities.WeightClass", "WeightClass")
                        .WithMany()
                        .HasForeignKey("WeightClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Meet");

                    b.Navigation("WeightClass");
                });

            modelBuilder.Entity("PowerliftMeet.Database.Entities.WeightClass", b =>
                {
                    b.HasOne("PowerliftMeet.Database.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
